words = [
    "approtect",
    "bundler",
    "buttonless",
    "checksums",
    "cmsis",
    "crc",
    "ebikes",
    "eraseall",
    "ficr",
    "oxlint",
    "patcher",
    "pselreset",
    "superduper",
    "uicr",
    "sdcfw",
    "astro"
]
