words = [
    "approtect",
    "astro",
    "bundler",
    "buttonless",
    "checksums",
    "cmsis",
    "crc",
    "dfu",
    "ebikes",
    "eraseall",
    "fflate",
    "ficr",
    "keygen",
    "nrf",
    "nrfutil",
    "oxlint",
    "patcher",
    "pselreset",
    "sdcfw",
    "secp",
    "superduper",
    "uicr",
    "undownloaded",
]
