words = [
    "approtect",
    "astro",
    "beforeunload",
    "bundler",
    "buttonless",
    "checksums",
    "cmsis",
    "crc",
    "dfu",
    "ebikes",
    "eraseall",
    "evenodd",
    "fflate",
    "ficr",
    "figcaption",
    "gnd",
    "keygen",
    "noopener",
    "nrf",
    "nrfutil",
    "oxlint",
    "patcher",
    "pselreset",
    "rarr",
    "sdcfw",
    "secp",
    "superduper",
    "swclk",
    "swdio",
    "uicr",
    "undownloaded",
    "usb",
]
